import type { MenuItem } from "./types";

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    permission: "dashboard:read",
    feature: "dashboard",
    roles: ["super_admin"],
  },
  {
    id: "services",
    label: "Services",
    path: "/services",
    permission: "services:read",
    feature: "services",
    roles: ["super_admin"],
  },
  {
    id: "analytics",
    label: "Analytics",
    path: "/dashboard/analytics",
    permission: "analytics:read",
    feature: "analytics",
    roles: ["super_admin"],
  },
  {
    id: "flows",
    label: "Flows",
    path: "/flows",
    permission: "flows:read",
    feature: "flows",
    roles: ["super_admin"],
  },
  {
    id: "agents",
    label: "Agents",
    path: "/agents",
    permission: "agents:read",
    feature: "agentConfig",
    roles: ["super_admin"],
  },
  {
    id: "stt_config",
    label: "STT Configuration",
    path: "/settings/stt",
    permission: "system:manage",
    feature: "sttConfig",
    roles: ["super_admin"],
  },
  {
    id: "tts_config",
    label: "TTS Configuration",
    path: "/settings/tts",
    permission: "system:manage",
    feature: "ttsConfig",
    roles: ["super_admin"],
  },
  {
    id: "users",
    label: "Users",
    path: "/admin/users",
    permission: "users:read",
    feature: "viewUsers",
    roles: ["super_admin"],
  },
  {
    id: "resellers",
    label: "Resellers",
    path: "/admin/resellers",
    permission: "resellers:read",
    feature: "viewResellers",
    roles: ["super_admin"],
  },
  {
    id: "admins",
    label: "Admins",
    path: "/admin/admins",
    permission: "system:manage",
    feature: "systemSettings",
    roles: ["super_admin"],
  },
  {
    id: "system_settings",
    label: "System Settings",
    path: "/admin/settings",
    permission: "system:manage",
    feature: "systemSettings",
    roles: ["super_admin"],
  },
  {
    id: "billing",
    label: "Billing",
    path: "/admin/billing",
    permission: "billing:read",
    feature: "billingSettings",
    roles: ["super_admin"],
  },
  {
    id: "api_keys",
    label: "API Keys",
    path: "/admin/api-keys",
    permission: "system:manage",
    feature: "systemSettings",
    roles: ["super_admin"],
  },
  {
    id: "audit_logs",
    label: "Audit Logs",
    path: "/admin/audit-logs",
    permission: "system:manage",
    feature: "systemSettings",
    roles: ["super_admin"],
  },
];
