"use server";

import connectDB from "@/lib/db";
import Agent from "@/features/agent/model";
import Flow from "@/features/flow/model";
import { revalidatePath } from "next/cache";

const getDefaultAgentStructure = () => ({
  workflow: {
    variables: {
      user_input: { type: "str" },
      llm_response: { type: "str" },
      conversation_history: { type: "list", default: [] },
      speak: { type: "str" },
      node_type: { type: "str" },
    },
    start_node: "greeting",
    nodes: {
      greeting: {
        type: "out",
        parameters: {
          out_dict: { speak: "Hello! How can I assist you today?" },
        },
        next: "ask_for_input",
      },
      ask_for_input: {
        type: "input",
        parameters: { input_variables: { user_input: "str" } },
        next: "transcription",
      },
      transcription: {
        type: "out",
        parameters: { variables: ["user_input"] },
        next: "llm",
      },
      llm: {
        type: "llm",
        parameters: {
          input_variables: {
            user_input: {
              type: "str",
              description: "The input text from the user.",
            },
          },
          prompt_template: "base_llm",
          system_prompt: "You are a guddu agent",
          service: "groq",
          model: "llama-3.3-70b-versatile",
          history_key: "conversation_history",
          llm_return_type: {
            speak: {
              type: "str",
              description:
                "The response generated by the LLM based on the user input.",
            },
          },
        },
        next: "response",
      },
      response: {
        type: "out",
        parameters: { variables: ["speak"] },
        next: "ask_for_input",
      },
    },
  },
});

export async function saveAgentConfiguration(flowId: string, rawData: any) {
  console.log("🟢 [Server] Received save request:", { flowId, rawData });

  try {
    await connectDB();
    const flow = await Flow.findById(flowId);
    if (!flow) return { success: false, message: "Flow not found" };

    let agent;
    if (flow.agent_id) agent = await Agent.findById(flow.agent_id);

    if (!agent) {
      agent = await Agent.create(getDefaultAgentStructure());
      flow.agent_id = agent._id;
      await flow.save();
    }

    let rawNodes = agent.get("workflow.nodes") || agent.workflow.nodes;

    let nodes = JSON.parse(JSON.stringify(rawNodes));

    console.log("🟢 [Server] Node Keys found:", Object.keys(nodes || {}));

    const llmNode = nodes?.llm;

    if (llmNode && llmNode.type === "llm") {
      if (!llmNode.parameters) llmNode.parameters = {};

      console.log("🟢 [Server] Updating LLM Node...");

      llmNode.parameters.system_prompt = rawData.systemPrompt;
      llmNode.parameters.service = rawData.provider;
      llmNode.parameters.model = rawData.model;

      nodes.llm = llmNode;

      agent.workflow.nodes = nodes;

      agent.markModified("workflow.nodes");

      await agent.save();

      console.log("🟢 [Server] Agent saved successfully");
    } else {
      console.log("🔴 [Server] LLM node not found. Structure:", nodes);
      return {
        success: false,
        message: "LLM node not found in agent configuration",
      };
    }

    revalidatePath(`/reseller/flow/${flowId}/agent`);
    revalidatePath(`/reseller/flow/${flowId}`);

    return { success: true, message: "Agent configuration saved" };
  } catch (error: any) {
    console.error("🔴 [Server] Save Agent Error:", error);
    return { success: false, message: "Internal Server Error" };
  }
}
