"use server";

import connectDB from "@/lib/db";
import Flow from "@/features/flow/model";
import User from "@/features/auth/model";
import STT from "@/features/stt/model";
import TTS from "@/features/tts/model";
import Agent from "@/features/agent/model";
import { getCurrentUser } from "@/lib/auth";
import { revalidatePath } from "next/cache";
import { randomBytes } from "crypto";

function generateApiKey(): string {
  const prefix = "vk_";
  const length = 64;
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

  const bytes = randomBytes(length);
  let result = "";

  for (let i = 0; i < length; i++) {
    result += chars[bytes[i] % chars.length];
  }

  return prefix + result;
}

export async function createFlow(flowName: string) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return { success: false, message: "Unauthorized" };
    }

    await connectDB();

    const dbUser = await User.findById(user._id).lean();
    if (!dbUser) {
      return { success: false, message: "User not found" };
    }

    const existingFlow = await Flow.findOne({
      _id: { $in: dbUser.flows },
      name: flowName.trim(),
    });

    if (existingFlow) {
      return {
        success: false,
        message: "You already have a flow with this name.",
      };
    }

    const newSTT = await STT.create({
      service: "deepgram",
      "model-name": "nova-3",
      language: "multi",
      prompt: "",
      temperature: 0,
      keyterms: "",
      channels: 1,
      sample_rate: 16000,
      sample_width: 2,
    });

    const newTTS = await TTS.create({
      service: "elevenlabs",
      "model-name": "eleven_multilingual_v3",
      voice_id: "1FcaCa84nUabCNNwbzBa",
    });

    const newAgent = await Agent.create({
      workflow: {
        variables: {
          user_input: { type: "str" },
          llm_response: { type: "str" },
          conversation_history: { type: "list", default: [] },
          speak: { type: "str" },
          node_type: { type: "str" },
        },
        start_node: "greeting",
        nodes: {
          greeting: {
            type: "out",
            parameters: {
              out_dict: { speak: "Hello! How can I assist you today?" },
            },
            next: "ask_for_input",
          },
          ask_for_input: {
            type: "input",
            parameters: { input_variables: { user_input: "str" } },
            next: "transcription",
          },
          transcription: {
            type: "out",
            parameters: { variables: ["user_input"] },
            next: "llm",
          },
          llm: {
            type: "llm",
            parameters: {
              input_variables: {
                user_input: {
                  type: "str",
                  description: "The input text from the user.",
                },
              },
              prompt_template: "base_llm",
              system_prompt: "You are a guddu agent",
              service: "groq",
              model: "llama-3.3-70b-versatile",
              history_key: "conversation_history",
              llm_return_type: {
                speak: {
                  type: "str",
                  description:
                    "The response generated by the LLM based on the user input.",
                },
              },
            },
            next: "response",
          },
          response: {
            type: "out",
            parameters: { variables: ["speak"] },
            next: "ask_for_input",
          },
        },
      },
    });

    const uniqueApiKey = generateApiKey();

    const newFlow = await Flow.create({
      name: flowName.trim(),
      api_key: uniqueApiKey,
      stt_id: newSTT._id,
      tts_id: newTTS._id,
      agent_id: newAgent._id,
      faces: [],
    });

    // 5. Link Flow to User
    await User.findByIdAndUpdate(user._id, {
      $push: { flows: newFlow._id },
    });

    console.log(
      `[Flow Created] ID: ${newFlow._id} | API Key: ${uniqueApiKey.slice(
        0,
        8
      )}...`
    );

    revalidatePath("/reseller/panel");

    return { success: true, flowId: newFlow._id.toString() };
  } catch (error: any) {
    console.error("Create Flow Error:", error);
    return {
      success: false,
      message: error.message || "Failed to create flow",
    };
  }
}

export async function deleteFlow(flowId: string) {
  try {
    const user = await getCurrentUser();
    if (!user) return { success: false, message: "Unauthorized" };

    await connectDB();

    const dbUser = await User.findById(user._id);
    if (!dbUser) {
      return { success: false, message: "User not found" };
    }

    const userFlows = dbUser.flows || [];
    const isOwner = userFlows.some((id) => id.toString() === flowId);

    if (!isOwner) {
      return { success: false, message: "You do not own this flow" };
    }

    const flow = await Flow.findById(flowId);

    if (!flow) {
      await User.findByIdAndUpdate(user._id, { $pull: { flows: flowId } });
      return { success: true };
    }

    if (flow.stt_id) await STT.findByIdAndDelete(flow.stt_id);
    if (flow.tts_id) await TTS.findByIdAndDelete(flow.tts_id);
    if (flow.agent_id) await Agent.findByIdAndDelete(flow.agent_id);

    await Flow.findByIdAndDelete(flowId);

    await User.findByIdAndUpdate(user._id, { $pull: { flows: flowId } });

    console.log(`[Flow Deleted] ID: ${flowId}`);

    revalidatePath("/reseller/panel");
    return { success: true };
  } catch (error: any) {
    console.error("Delete Flow Error:", error);
    return { success: false, message: "Internal Server Error" };
  }
}
