"use server";

import connectDB from "@/lib/db";
import Flow from "@/features/flow/model";
import User from "@/features/auth/model";
import STT from "@/features/stt/model";
import TTS from "@/features/tts/model";
import Agent from "@/features/agent/model";
import { getCurrentUser } from "@/lib/auth";
import { revalidatePath } from "next/cache";
import { randomBytes } from "crypto";

function generateApiKey(): string {
  const prefix = "vk_";
  const length = 64;
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

  const bytes = randomBytes(length);
  let result = "";

  for (let i = 0; i < length; i++) {
    result += chars[bytes[i] % chars.length];
  }

  return prefix + result;
}

// --- WORKFLOW DEFINITIONS ---

const STANDARD_WORKFLOW = {
  variables: {
    user_input: { type: "str" },
    llm_response: { type: "str" },
    conversation_history: { type: "list", default: [] },
    speak: { type: "str" },
    node_type: { type: "str" },
  },
  start_node: "greeting",
  nodes: {
    greeting: {
      type: "out",
      parameters: {
        out_dict: { speak: "Hello! How can I assist you today?" },
      },
      next: "ask_for_input",
    },
    ask_for_input: {
      type: "input",
      parameters: { input_variables: { user_input: "str" } },
      next: "transcription",
    },
    transcription: {
      type: "out",
      parameters: { variables: ["user_input"] },
      next: "llm",
    },
    llm: {
      type: "llm",
      parameters: {
        input_variables: {
          user_input: {
            type: "str",
            description: "The input text from the user.",
          },
        },
        prompt_template: "base_llm",
        system_prompt: "You are a helpful agent",
        service: "groq",
        model: "llama-3.3-70b-versatile",
        history_key: "conversation_history",
        emotion: false,
        emotion_tts: "eleven_v3",
        llm_return_type: {
          speak: {
            type: "str",
            description:
              "The response generated by the LLM based on the user input.",
          },
        },
      },
      next: "response",
    },
    response: {
      type: "out",
      parameters: { variables: ["speak"] },
      next: "ask_for_input",
    },
  },
};

const ROLEPLAY_WORKFLOW = {
  variables: {
    user_input: { type: "str" },
    llm_response: { type: "str" },
    end_diagnosis: { type: "str" },
    conversation_history: { type: "list", default: [] },
    score: { type: "float" },
    speak: { type: "str" },
    node_type: { type: "str" },
    trainee_name: { type: "str", default: "Ayush" },
    summary: { type: "str" },
  },
  start_node: "greeting",
  nodes: {
    greeting: {
      type: "out",
      parameters: {
        out_dict: {
          speak:
            "Are you the new guard? Finally. Someone parked in my spot. Again! What's the point of paying so much for security if you all just walk around? Are you going to do something or just stand there ?",
        },
      },
      next: "input",
    },
    input: {
      type: "input",
      parameters: {
        input_variables: {
          user_input: "str",
        },
      },
      next: ["transcription", "llm"],
    },
    transcription: {
      type: "out",
      parameters: {
        variables: ["user_input"],
      },
    },
    llm: {
      type: "llm",
      parameters: {
        input_variables: {
          user_input: {
            type: "str",
            description: "The input text from the user.",
          },
          trainee_name: {
            type: "str",
            description: "Name of the trainee you are talking with",
          },
        },
        prompt_template: "base_llm",
        system_prompt:
          "User the scenario only as defined, use only small 'yes' or 'no' for end_diagnosis",
        service: "groq",
        model: "llama-3.3-70b-versatile",
        history_key: "conversation_history",
        emotion: false,
        emotion_tts: "eleven_v3",
        llm_return_type: {
          speak: {
            type: "str",
            description:
              "The response generated by the LLM based on the user input.",
          },
          end_diagnosis: {
            type: "str",
            description: "Indicates whether the diagnosis session should end.",
          },
        },
      },
      next: ["response", "judge_if_diagnosis_is_ended"],
    },
    response: {
      type: "out",
      parameters: {
        variables: ["speak", "end_diagnosis"],
      },
    },
    judge_if_diagnosis_is_ended: {
      type: "conditional",
      parameters: {
        input_variables: {
          end_diagnosis: {},
        },
        mappings: {
          yes: ["feedback", "summary"],
          no: "input",
        },
      },
    },
    feedback: {
      type: "llm",
      parameters: {
        input_variables: {
          conversation_history: {
            type: "list",
            description: "the conversation hsitory of the diagnosis",
          },
        },
        prompt_template: "base_llm",
        system_prompt:
          "# EVALUATION CRITERIA You MUST evaluate the trainee on the following four criteria: 1.  **Communication Skills:** Did they speak clearly? Were they polite but firm? Did they listen actively? 2.  **Problem-Solving:** Did they correctly identify the problem? Did they offer valid solutions? Did they follow procedure? 3.  **Emotional Control:** Did they remain calm and professional? Did they de-escalate the situation, or did they get flustered or argumentative? 4.  **Professionalism:** Did they maintain a professional demeanor? Did they avoid breaking character or getting sidetracked? ",
        service: "groq",
        model: "llama-3.3-70b-versatile",
        history_key: "feedback_conversation_history",
        emotion: false,
        emotion_tts: "eleven_v3",
        llm_return_type: {
          llm_response: {
            type: "str",
            description:
              "the evaluation report, it shall be in a markdown format with a table with columsn as 'Criteria' , 'Rating (1-10)' , 'Brief Justification'",
          },
        },
      },
      next: ["feedbacko"],
    },
    summary: {
      type: "llm",
      parameters: {
        input_variables: {
          conversation_history: {
            type: "list",
            description: "the conversation hsitory of the diagnosis",
          },
        },
        prompt_template: "base_llm",
        system_prompt:
          "Provide summary of the session as **What Went Well:** * [Provide 2-3 specific, positive points, referencing the transcript] **Areas for Improvement:** * [Provide 2-3 specific, constructive points. Explain WHAT they could have done differently and WHY] ",
        service: "groq",
        model: "llama-3.3-70b-versatile",
        history_key: "feedback_conversation_history",
        emotion: false,
        emotion_tts: "eleven_v3",
        llm_return_type: {
          summary: {
            type: "str",
            description: "the content for summary",
          },
        },
      },
      next: "summaryo",
    },
    summaryo: {
      type: "out",
      parameters: {
        variables: ["summary"],
      },
    },
    feedbacko: {
      type: "out",
      parameters: {
        variables: ["llm_response"],
      },
    },
  },
};

// --- ACTION FUNCTION ---

export async function createFlow(
  flowName: string,
  isRolePlaying: boolean = false,
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return { success: false, message: "Unauthorized" };
    }

    await connectDB();

    const dbUser = await User.findById(user._id).lean();
    if (!dbUser) {
      return { success: false, message: "User not found" };
    }

    const existingFlow = await Flow.findOne({
      _id: { $in: dbUser.flows },
      name: flowName.trim(),
    });

    if (existingFlow) {
      return {
        success: false,
        message: "You already have a flow with this name.",
      };
    }

    const newSTT = await STT.create({
      service: "assemblyai",
      "model-name": "universal",
      language: "",
      prompt: "",
      temperature: 0,
      keyterms: "",
      channels: 1,
      sample_rate: 16000,
      sample_width: 2,
    });

    const newTTS = await TTS.create({
      service: "elevenlabs",
      "model-name": "eleven_v3",
      voice_id: "1FcaCa84nUabCNNwbzBa",
    });

    // SELECT WORKFLOW
    const selectedWorkflow = isRolePlaying
      ? ROLEPLAY_WORKFLOW
      : STANDARD_WORKFLOW;

    const newAgent = await Agent.create({
      workflow: selectedWorkflow,
    });

    const uniqueApiKey = generateApiKey();

    const newFlow = await Flow.create({
      name: flowName.trim(),
      api_key: uniqueApiKey,
      stt_id: newSTT._id,
      tts_id: newTTS._id,
      agent_id: newAgent._id,
      "max-silence-counter": 20,

      faces: [],
    });

    await User.findByIdAndUpdate(user._id, {
      $push: { flows: newFlow._id },
    });

    console.log(
      `[Flow Created] ID: ${newFlow._id} | RolePlay: ${isRolePlaying}`,
    );

    revalidatePath("/reseller/panel");

    return { success: true, flowId: newFlow._id.toString() };
  } catch (error: any) {
    console.error("Create Flow Error:", error);
    return {
      success: false,
      message: error.message || "Failed to create flow",
    };
  }
}

export async function deleteFlow(flowId: string) {
  try {
    const user = await getCurrentUser();
    if (!user) return { success: false, message: "Unauthorized" };

    await connectDB();

    const dbUser = await User.findById(user._id);
    if (!dbUser) {
      return { success: false, message: "User not found" };
    }

    const userFlows = dbUser.flows || [];
    const isOwner = userFlows.some((id: any) => id.toString() === flowId);

    if (!isOwner) {
      return { success: false, message: "You do not own this flow" };
    }

    const flow = await Flow.findById(flowId);

    if (!flow) {
      await User.findByIdAndUpdate(user._id, { $pull: { flows: flowId } });
      return { success: true };
    }

    if (flow.stt_id) await STT.findByIdAndDelete(flow.stt_id);
    if (flow.tts_id) await TTS.findByIdAndDelete(flow.tts_id);
    if (flow.agent_id) await Agent.findByIdAndDelete(flow.agent_id);

    await Flow.findByIdAndDelete(flowId);

    await User.findByIdAndUpdate(user._id, { $pull: { flows: flowId } });

    console.log(`[Flow Deleted] ID: ${flowId}`);

    revalidatePath("/reseller/panel");
    return { success: true };
  } catch (error: any) {
    console.error("Delete Flow Error:", error);
    return { success: false, message: "Internal Server Error" };
  }
}
export async function updateFlowSilence(flowId: string, counterValue: number) {
  try {
    const user = await getCurrentUser();
    if (!user) return { success: false, message: "Unauthorized" };

    await connectDB();

    const dbUser = await User.findById(user._id);

    if (!dbUser) {
      return { success: false, message: "User not found" };
    }

    const userFlows = dbUser.flows || [];

    const isOwner = userFlows.some((id: any) => id.toString() === flowId);

    if (!isOwner) {
      return { success: false, message: "Unauthorized" };
    }

    await Flow.findByIdAndUpdate(flowId, {
      "max-silence-counter": counterValue,
    });

    revalidatePath("/reseller/panel");
    return { success: true };
  } catch (error: any) {
    console.error("Update Silence Error:", error);
    return { success: false, message: "Failed to update" };
  }
}
