/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardDashboardRouteImport } from './routes/dashboard/dashboard'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardUserRouteRouteImport } from './routes/dashboard/user/route'
import { Route as DashboardSuperadminRouteRouteImport } from './routes/dashboard/superadmin/route'
import { Route as DashboardResellerRouteRouteImport } from './routes/dashboard/reseller/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardUserIndexRouteImport } from './routes/dashboard/user/index'
import { Route as DashboardSuperadminIndexRouteImport } from './routes/dashboard/superadmin/index'
import { Route as DashboardResellerIndexRouteImport } from './routes/dashboard/reseller/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardUserFlowsRouteImport } from './routes/dashboard/user/flows'
import { Route as DashboardSuperadminUsersRouteImport } from './routes/dashboard/superadmin/users'
import { Route as DashboardSuperadminResllersRouteImport } from './routes/dashboard/superadmin/resllers'
import { Route as DashboardSuperadminAdminRouteImport } from './routes/dashboard/superadmin/admin'
import { Route as DashboardResellerUsersRouteImport } from './routes/dashboard/reseller/users'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardUserRouteRoute = DashboardUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSuperadminRouteRoute =
  DashboardSuperadminRouteRouteImport.update({
    id: '/superadmin',
    path: '/superadmin',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardResellerRouteRoute = DashboardResellerRouteRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUserRouteRoute,
} as any)
const DashboardSuperadminIndexRoute =
  DashboardSuperadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardResellerIndexRoute = DashboardResellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardResellerRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardUserFlowsRoute = DashboardUserFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DashboardUserRouteRoute,
} as any)
const DashboardSuperadminUsersRoute =
  DashboardSuperadminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardSuperadminResllersRoute =
  DashboardSuperadminResllersRouteImport.update({
    id: '/resllers',
    path: '/resllers',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardSuperadminAdminRoute =
  DashboardSuperadminAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardResellerUsersRoute = DashboardResellerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardResellerRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/reseller': typeof DashboardResellerRouteRouteWithChildren
  '/dashboard/superadmin': typeof DashboardSuperadminRouteRouteWithChildren
  '/dashboard/user': typeof DashboardUserRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/reseller/users': typeof DashboardResellerUsersRoute
  '/dashboard/superadmin/admin': typeof DashboardSuperadminAdminRoute
  '/dashboard/superadmin/resllers': typeof DashboardSuperadminResllersRoute
  '/dashboard/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/dashboard/user/flows': typeof DashboardUserFlowsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/reseller/': typeof DashboardResellerIndexRoute
  '/dashboard/superadmin/': typeof DashboardSuperadminIndexRoute
  '/dashboard/user/': typeof DashboardUserIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/reseller/users': typeof DashboardResellerUsersRoute
  '/dashboard/superadmin/admin': typeof DashboardSuperadminAdminRoute
  '/dashboard/superadmin/resllers': typeof DashboardSuperadminResllersRoute
  '/dashboard/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/dashboard/user/flows': typeof DashboardUserFlowsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/reseller': typeof DashboardResellerIndexRoute
  '/dashboard/superadmin': typeof DashboardSuperadminIndexRoute
  '/dashboard/user': typeof DashboardUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/reseller': typeof DashboardResellerRouteRouteWithChildren
  '/dashboard/superadmin': typeof DashboardSuperadminRouteRouteWithChildren
  '/dashboard/user': typeof DashboardUserRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/reseller/users': typeof DashboardResellerUsersRoute
  '/dashboard/superadmin/admin': typeof DashboardSuperadminAdminRoute
  '/dashboard/superadmin/resllers': typeof DashboardSuperadminResllersRoute
  '/dashboard/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/dashboard/user/flows': typeof DashboardUserFlowsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/reseller/': typeof DashboardResellerIndexRoute
  '/dashboard/superadmin/': typeof DashboardSuperadminIndexRoute
  '/dashboard/user/': typeof DashboardUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/reseller'
    | '/dashboard/superadmin'
    | '/dashboard/user'
    | '/auth/login'
    | '/dashboard/dashboard'
    | '/dashboard/admin/users'
    | '/dashboard/reseller/users'
    | '/dashboard/superadmin/admin'
    | '/dashboard/superadmin/resllers'
    | '/dashboard/superadmin/users'
    | '/dashboard/user/flows'
    | '/dashboard/admin/'
    | '/dashboard/reseller/'
    | '/dashboard/superadmin/'
    | '/dashboard/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/dashboard'
    | '/dashboard/admin/users'
    | '/dashboard/reseller/users'
    | '/dashboard/superadmin/admin'
    | '/dashboard/superadmin/resllers'
    | '/dashboard/superadmin/users'
    | '/dashboard/user/flows'
    | '/dashboard/admin'
    | '/dashboard/reseller'
    | '/dashboard/superadmin'
    | '/dashboard/user'
  id:
    | '__root__'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/reseller'
    | '/dashboard/superadmin'
    | '/dashboard/user'
    | '/auth/login'
    | '/dashboard/dashboard'
    | '/dashboard/admin/users'
    | '/dashboard/reseller/users'
    | '/dashboard/superadmin/admin'
    | '/dashboard/superadmin/resllers'
    | '/dashboard/superadmin/users'
    | '/dashboard/user/flows'
    | '/dashboard/admin/'
    | '/dashboard/reseller/'
    | '/dashboard/superadmin/'
    | '/dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dashboard': {
      id: '/dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/superadmin': {
      id: '/dashboard/superadmin'
      path: '/superadmin'
      fullPath: '/dashboard/superadmin'
      preLoaderRoute: typeof DashboardSuperadminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reseller': {
      id: '/dashboard/reseller'
      path: '/reseller'
      fullPath: '/dashboard/reseller'
      preLoaderRoute: typeof DashboardResellerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/user/': {
      id: '/dashboard/user/'
      path: '/'
      fullPath: '/dashboard/user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardUserRouteRoute
    }
    '/dashboard/superadmin/': {
      id: '/dashboard/superadmin/'
      path: '/'
      fullPath: '/dashboard/superadmin/'
      preLoaderRoute: typeof DashboardSuperadminIndexRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/dashboard/reseller/': {
      id: '/dashboard/reseller/'
      path: '/'
      fullPath: '/dashboard/reseller/'
      preLoaderRoute: typeof DashboardResellerIndexRouteImport
      parentRoute: typeof DashboardResellerRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/user/flows': {
      id: '/dashboard/user/flows'
      path: '/flows'
      fullPath: '/dashboard/user/flows'
      preLoaderRoute: typeof DashboardUserFlowsRouteImport
      parentRoute: typeof DashboardUserRouteRoute
    }
    '/dashboard/superadmin/users': {
      id: '/dashboard/superadmin/users'
      path: '/users'
      fullPath: '/dashboard/superadmin/users'
      preLoaderRoute: typeof DashboardSuperadminUsersRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/dashboard/superadmin/resllers': {
      id: '/dashboard/superadmin/resllers'
      path: '/resllers'
      fullPath: '/dashboard/superadmin/resllers'
      preLoaderRoute: typeof DashboardSuperadminResllersRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/dashboard/superadmin/admin': {
      id: '/dashboard/superadmin/admin'
      path: '/admin'
      fullPath: '/dashboard/superadmin/admin'
      preLoaderRoute: typeof DashboardSuperadminAdminRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/dashboard/reseller/users': {
      id: '/dashboard/reseller/users'
      path: '/users'
      fullPath: '/dashboard/reseller/users'
      preLoaderRoute: typeof DashboardResellerUsersRouteImport
      parentRoute: typeof DashboardResellerRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardResellerRouteRouteChildren {
  DashboardResellerUsersRoute: typeof DashboardResellerUsersRoute
  DashboardResellerIndexRoute: typeof DashboardResellerIndexRoute
}

const DashboardResellerRouteRouteChildren: DashboardResellerRouteRouteChildren =
  {
    DashboardResellerUsersRoute: DashboardResellerUsersRoute,
    DashboardResellerIndexRoute: DashboardResellerIndexRoute,
  }

const DashboardResellerRouteRouteWithChildren =
  DashboardResellerRouteRoute._addFileChildren(
    DashboardResellerRouteRouteChildren,
  )

interface DashboardSuperadminRouteRouteChildren {
  DashboardSuperadminAdminRoute: typeof DashboardSuperadminAdminRoute
  DashboardSuperadminResllersRoute: typeof DashboardSuperadminResllersRoute
  DashboardSuperadminUsersRoute: typeof DashboardSuperadminUsersRoute
  DashboardSuperadminIndexRoute: typeof DashboardSuperadminIndexRoute
}

const DashboardSuperadminRouteRouteChildren: DashboardSuperadminRouteRouteChildren =
  {
    DashboardSuperadminAdminRoute: DashboardSuperadminAdminRoute,
    DashboardSuperadminResllersRoute: DashboardSuperadminResllersRoute,
    DashboardSuperadminUsersRoute: DashboardSuperadminUsersRoute,
    DashboardSuperadminIndexRoute: DashboardSuperadminIndexRoute,
  }

const DashboardSuperadminRouteRouteWithChildren =
  DashboardSuperadminRouteRoute._addFileChildren(
    DashboardSuperadminRouteRouteChildren,
  )

interface DashboardUserRouteRouteChildren {
  DashboardUserFlowsRoute: typeof DashboardUserFlowsRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
}

const DashboardUserRouteRouteChildren: DashboardUserRouteRouteChildren = {
  DashboardUserFlowsRoute: DashboardUserFlowsRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
}

const DashboardUserRouteRouteWithChildren =
  DashboardUserRouteRoute._addFileChildren(DashboardUserRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardResellerRouteRoute: typeof DashboardResellerRouteRouteWithChildren
  DashboardSuperadminRouteRoute: typeof DashboardSuperadminRouteRouteWithChildren
  DashboardUserRouteRoute: typeof DashboardUserRouteRouteWithChildren
  DashboardDashboardRoute: typeof DashboardDashboardRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardResellerRouteRoute: DashboardResellerRouteRouteWithChildren,
  DashboardSuperadminRouteRoute: DashboardSuperadminRouteRouteWithChildren,
  DashboardUserRouteRoute: DashboardUserRouteRouteWithChildren,
  DashboardDashboardRoute: DashboardDashboardRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
