/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardUserRouteRouteImport } from './routes/_dashboard/user/route'
import { Route as DashboardSuperadminRouteRouteImport } from './routes/_dashboard/superadmin/route'
import { Route as DashboardResellerRouteRouteImport } from './routes/_dashboard/reseller/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/_dashboard/admin/route'
import { Route as DashboardUserIndexRouteImport } from './routes/_dashboard/user/index'
import { Route as DashboardSuperadminIndexRouteImport } from './routes/_dashboard/superadmin/index'
import { Route as DashboardResellerIndexRouteImport } from './routes/_dashboard/reseller/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as DashboardUserFlowsRouteImport } from './routes/_dashboard/user/flows'
import { Route as DashboardSuperadminUsersRouteImport } from './routes/_dashboard/superadmin/users'
import { Route as DashboardSuperadminUiConfigRouteImport } from './routes/_dashboard/superadmin/ui-config'
import { Route as DashboardSuperadminResellersRouteImport } from './routes/_dashboard/superadmin/resellers'
import { Route as DashboardSuperadminAdminsRouteImport } from './routes/_dashboard/superadmin/admins'
import { Route as DashboardResellerUsersRouteImport } from './routes/_dashboard/reseller/users'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard/admin/users'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardUserRouteRoute = DashboardUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSuperadminRouteRoute =
  DashboardSuperadminRouteRouteImport.update({
    id: '/superadmin',
    path: '/superadmin',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardResellerRouteRoute = DashboardResellerRouteRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUserRouteRoute,
} as any)
const DashboardSuperadminIndexRoute =
  DashboardSuperadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardResellerIndexRoute = DashboardResellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardResellerRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardUserFlowsRoute = DashboardUserFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DashboardUserRouteRoute,
} as any)
const DashboardSuperadminUsersRoute =
  DashboardSuperadminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardSuperadminUiConfigRoute =
  DashboardSuperadminUiConfigRouteImport.update({
    id: '/ui-config',
    path: '/ui-config',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardSuperadminResellersRoute =
  DashboardSuperadminResellersRouteImport.update({
    id: '/resellers',
    path: '/resellers',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardSuperadminAdminsRoute =
  DashboardSuperadminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => DashboardSuperadminRouteRoute,
  } as any)
const DashboardResellerUsersRoute = DashboardResellerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardResellerRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardRouteRouteWithChildren
  '/admin': typeof DashboardAdminRouteRouteWithChildren
  '/reseller': typeof DashboardResellerRouteRouteWithChildren
  '/superadmin': typeof DashboardSuperadminRouteRouteWithChildren
  '/user': typeof DashboardUserRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/reseller/users': typeof DashboardResellerUsersRoute
  '/superadmin/admins': typeof DashboardSuperadminAdminsRoute
  '/superadmin/resellers': typeof DashboardSuperadminResellersRoute
  '/superadmin/ui-config': typeof DashboardSuperadminUiConfigRoute
  '/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/user/flows': typeof DashboardUserFlowsRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/reseller/': typeof DashboardResellerIndexRoute
  '/superadmin/': typeof DashboardSuperadminIndexRoute
  '/user/': typeof DashboardUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/reseller/users': typeof DashboardResellerUsersRoute
  '/superadmin/admins': typeof DashboardSuperadminAdminsRoute
  '/superadmin/resellers': typeof DashboardSuperadminResellersRoute
  '/superadmin/ui-config': typeof DashboardSuperadminUiConfigRoute
  '/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/user/flows': typeof DashboardUserFlowsRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/reseller': typeof DashboardResellerIndexRoute
  '/superadmin': typeof DashboardSuperadminIndexRoute
  '/user': typeof DashboardUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/_dashboard/reseller': typeof DashboardResellerRouteRouteWithChildren
  '/_dashboard/superadmin': typeof DashboardSuperadminRouteRouteWithChildren
  '/_dashboard/user': typeof DashboardUserRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/_dashboard/reseller/users': typeof DashboardResellerUsersRoute
  '/_dashboard/superadmin/admins': typeof DashboardSuperadminAdminsRoute
  '/_dashboard/superadmin/resellers': typeof DashboardSuperadminResellersRoute
  '/_dashboard/superadmin/ui-config': typeof DashboardSuperadminUiConfigRoute
  '/_dashboard/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/_dashboard/user/flows': typeof DashboardUserFlowsRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/reseller/': typeof DashboardResellerIndexRoute
  '/_dashboard/superadmin/': typeof DashboardSuperadminIndexRoute
  '/_dashboard/user/': typeof DashboardUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reseller'
    | '/superadmin'
    | '/user'
    | '/login'
    | '/dashboard'
    | '/admin/users'
    | '/reseller/users'
    | '/superadmin/admins'
    | '/superadmin/resellers'
    | '/superadmin/ui-config'
    | '/superadmin/users'
    | '/user/flows'
    | '/admin/'
    | '/reseller/'
    | '/superadmin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/users'
    | '/reseller/users'
    | '/superadmin/admins'
    | '/superadmin/resellers'
    | '/superadmin/ui-config'
    | '/superadmin/users'
    | '/user/flows'
    | '/admin'
    | '/reseller'
    | '/superadmin'
    | '/user'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_dashboard/admin'
    | '/_dashboard/reseller'
    | '/_dashboard/superadmin'
    | '/_dashboard/user'
    | '/_auth/login'
    | '/_dashboard/dashboard'
    | '/_dashboard/admin/users'
    | '/_dashboard/reseller/users'
    | '/_dashboard/superadmin/admins'
    | '/_dashboard/superadmin/resellers'
    | '/_dashboard/superadmin/ui-config'
    | '/_dashboard/superadmin/users'
    | '/_dashboard/user/flows'
    | '/_dashboard/admin/'
    | '/_dashboard/reseller/'
    | '/_dashboard/superadmin/'
    | '/_dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/user': {
      id: '/_dashboard/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof DashboardUserRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/superadmin': {
      id: '/_dashboard/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof DashboardSuperadminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/reseller': {
      id: '/_dashboard/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof DashboardResellerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/user/': {
      id: '/_dashboard/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardUserRouteRoute
    }
    '/_dashboard/superadmin/': {
      id: '/_dashboard/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof DashboardSuperadminIndexRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/_dashboard/reseller/': {
      id: '/_dashboard/reseller/'
      path: '/'
      fullPath: '/reseller/'
      preLoaderRoute: typeof DashboardResellerIndexRouteImport
      parentRoute: typeof DashboardResellerRouteRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_dashboard/user/flows': {
      id: '/_dashboard/user/flows'
      path: '/flows'
      fullPath: '/user/flows'
      preLoaderRoute: typeof DashboardUserFlowsRouteImport
      parentRoute: typeof DashboardUserRouteRoute
    }
    '/_dashboard/superadmin/users': {
      id: '/_dashboard/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof DashboardSuperadminUsersRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/_dashboard/superadmin/ui-config': {
      id: '/_dashboard/superadmin/ui-config'
      path: '/ui-config'
      fullPath: '/superadmin/ui-config'
      preLoaderRoute: typeof DashboardSuperadminUiConfigRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/_dashboard/superadmin/resellers': {
      id: '/_dashboard/superadmin/resellers'
      path: '/resellers'
      fullPath: '/superadmin/resellers'
      preLoaderRoute: typeof DashboardSuperadminResellersRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/_dashboard/superadmin/admins': {
      id: '/_dashboard/superadmin/admins'
      path: '/admins'
      fullPath: '/superadmin/admins'
      preLoaderRoute: typeof DashboardSuperadminAdminsRouteImport
      parentRoute: typeof DashboardSuperadminRouteRoute
    }
    '/_dashboard/reseller/users': {
      id: '/_dashboard/reseller/users'
      path: '/users'
      fullPath: '/reseller/users'
      preLoaderRoute: typeof DashboardResellerUsersRouteImport
      parentRoute: typeof DashboardResellerRouteRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardResellerRouteRouteChildren {
  DashboardResellerUsersRoute: typeof DashboardResellerUsersRoute
  DashboardResellerIndexRoute: typeof DashboardResellerIndexRoute
}

const DashboardResellerRouteRouteChildren: DashboardResellerRouteRouteChildren =
  {
    DashboardResellerUsersRoute: DashboardResellerUsersRoute,
    DashboardResellerIndexRoute: DashboardResellerIndexRoute,
  }

const DashboardResellerRouteRouteWithChildren =
  DashboardResellerRouteRoute._addFileChildren(
    DashboardResellerRouteRouteChildren,
  )

interface DashboardSuperadminRouteRouteChildren {
  DashboardSuperadminAdminsRoute: typeof DashboardSuperadminAdminsRoute
  DashboardSuperadminResellersRoute: typeof DashboardSuperadminResellersRoute
  DashboardSuperadminUiConfigRoute: typeof DashboardSuperadminUiConfigRoute
  DashboardSuperadminUsersRoute: typeof DashboardSuperadminUsersRoute
  DashboardSuperadminIndexRoute: typeof DashboardSuperadminIndexRoute
}

const DashboardSuperadminRouteRouteChildren: DashboardSuperadminRouteRouteChildren =
  {
    DashboardSuperadminAdminsRoute: DashboardSuperadminAdminsRoute,
    DashboardSuperadminResellersRoute: DashboardSuperadminResellersRoute,
    DashboardSuperadminUiConfigRoute: DashboardSuperadminUiConfigRoute,
    DashboardSuperadminUsersRoute: DashboardSuperadminUsersRoute,
    DashboardSuperadminIndexRoute: DashboardSuperadminIndexRoute,
  }

const DashboardSuperadminRouteRouteWithChildren =
  DashboardSuperadminRouteRoute._addFileChildren(
    DashboardSuperadminRouteRouteChildren,
  )

interface DashboardUserRouteRouteChildren {
  DashboardUserFlowsRoute: typeof DashboardUserFlowsRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
}

const DashboardUserRouteRouteChildren: DashboardUserRouteRouteChildren = {
  DashboardUserFlowsRoute: DashboardUserFlowsRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
}

const DashboardUserRouteRouteWithChildren =
  DashboardUserRouteRoute._addFileChildren(DashboardUserRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardResellerRouteRoute: typeof DashboardResellerRouteRouteWithChildren
  DashboardSuperadminRouteRoute: typeof DashboardSuperadminRouteRouteWithChildren
  DashboardUserRouteRoute: typeof DashboardUserRouteRouteWithChildren
  DashboardDashboardRoute: typeof DashboardDashboardRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardResellerRouteRoute: DashboardResellerRouteRouteWithChildren,
  DashboardSuperadminRouteRoute: DashboardSuperadminRouteRouteWithChildren,
  DashboardUserRouteRoute: DashboardUserRouteRouteWithChildren,
  DashboardDashboardRoute: DashboardDashboardRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
